/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *            Major functions: _sbrk() denies all C-library heap growth.
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * @brief Refuse all C-library heap growth under Atlas's static-memory policy.
 * @param incr Requested change; positive, zero and negative values all fail.
 * @return (void *)-1 with errno=ENOMEM; never hands out writable memory.
 * @note The generated allocator ignored the zero-heap setting and could grow
 *       toward the MPU guard. Keep this override when regenerating CubeMX code.
 */
void *_sbrk(ptrdiff_t incr)
{
  (void)incr;
  errno = ENOMEM;
  return (void *)-1;
}

#if defined(__PICOLIBC__)
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);
#endif
